### ISSUE TITLE
Does not start test/main.js

### ISSUE THREAD

**Issue by treasurebox** [guerrerocarlos/node-airplay-js#12]
With latest commit as of now on OS X El Capitan, I get following:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 192.168.5.129:5353
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:440:9)
    at process._tickCallback (node.js:346:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by treasurebox** [comment]
The real issue here is that by chance, port 5353 was already used on my system, but it would be nice if the player would choose a free port.
